### ISSUE TITLE
server lag???

### ISSUE THREAD

**Issue by ppappila** [Shad0wB1ade/Solar-Expansion-Lang#2]
does not crash the server right away...but this is something amiss. Please check it out...

running minecraft 1.7.1.10 forge 1208

from the server log file..

[23:21:57] [Server thread/INFO] [OpenEye]: openeye.logic.ThrowableLogger.processThrowable(ThrowableLogger.java:84): Limit reached for location tile_entity_write, skipping java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
[23:21:57] [Server thread/ERROR] [FML]: A TileEntity type com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
    at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
    at com.shad0wb1ade.solarexpansion.tile.BaseModTileEntity.func_145841_b(BaseModTileEntity.java:28) ~[BaseModTileEntity.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:808) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[23:21:57] [Server thread/INFO] [OpenEye]: openeye.logic.ThrowableLogger.processThrowable(ThrowableLogger.java:84): Limit reached for location tile_entity_write, skipping java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
[23:21:57] [Server thread/ERROR] [FML]: A TileEntity type com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
    at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
    at com.shad0wb1ade.solarexpansion.tile.BaseModTileEntity.func_145841_b(BaseModTileEntity.java:28) ~[BaseModTileEntity.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:808) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[23:21:57] [Server thread/INFO] [OpenEye]: openeye.logic.ThrowableLogger.processThrowable(ThrowableLogger.java:84): Limit reached for location tile_entity_write, skipping java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
[23:21:57] [Server thread/ERROR] [FML]: A TileEntity type com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
    at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
    at com.shad0wb1ade.solarexpansion.tile.BaseModTileEntity.func_145841_b(BaseModTileEntity.java:28) ~[BaseModTileEntity.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:808) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[23:22:25] [Server thread/INFO]: ppappila lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[23:22:25] [Server thread/INFO]: §c[OP] §rppappila left the game
[23:22:42] [Server thread/INFO] [OpenEye]: openeye.logic.ThrowableLogger.processThrowable(ThrowableLogger.java:84): Limit reached for location tile_entity_write, skipping java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
[23:22:42] [Server thread/ERROR] [FML]: A TileEntity type com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
    at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
    at com.shad0wb1ade.solarexpansion.tile.BaseModTileEntity.func_145841_b(BaseModTileEntity.java:28) ~[BaseModTileEntity.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:808) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[23:22:42] [Server thread/INFO] [OpenEye]: openeye.logic.ThrowableLogger.processThrowable(ThrowableLogger.java:84): Limit reached for location tile_entity_write, skipping java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
[23:22:42] [Server thread/ERROR] [FML]: A TileEntity type com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
    at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
    at com.shad0wb1ade.solarexpansion.tile.BaseModTileEntity.func_145841_b(BaseModTileEntity.java:28) ~[BaseModTileEntity.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:808) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[23:22:42] [Server thread/INFO] [OpenEye]: openeye.logic.ThrowableLogger.processThrowable(ThrowableLogger.java:84): Limit reached for location tile_entity_write, skipping java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
[23:22:42] [Server thread/ERROR] [FML]: A TileEntity type com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
    at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
    at com.shad0wb1ade.solarexpansion.tile.BaseModTileEntity.func_145841_b(BaseModTileEntity.java:28) ~[BaseModTileEntity.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:808) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[23:22:42] [Server thread/INFO] [OpenEye]: openeye.logic.ThrowableLogger.processThrowable(ThrowableLogger.java:84): Limit reached for location tile_entity_write, skipping java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
[23:22:42] [Server thread/ERROR] [FML]: A TileEntity type com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
    at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
    at com.shad0wb1ade.solarexpansion.tile.BaseModTileEntity.func_145841_b(BaseModTileEntity.java:28) ~[BaseModTileEntity.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:808) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[23:23:27] [Server thread/INFO] [OpenEye]: openeye.logic.ThrowableLogger.processThrowable(ThrowableLogger.java:84): Limit reached for location tile_entity_write, skipping java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
[23:23:27] [Server thread/ERROR] [FML]: A TileEntity type com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
    at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
    at com.shad0wb1ade.solarexpansion.tile.BaseModTileEntity.func_145841_b(BaseModTileEntity.java:28) ~[BaseModTileEntity.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:808) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[23:23:27] [Server thread/INFO] [OpenEye]: openeye.logic.ThrowableLogger.processThrowable(ThrowableLogger.java:84): Limit reached for location tile_entity_write, skipping java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
[23:23:27] [Server thread/ERROR] [FML]: A TileEntity type com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
    at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
    at com.shad0wb1ade.solarexpansion.tile.BaseModTileEntity.func_145841_b(BaseModTileEntity.java:28) ~[BaseModTileEntity.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:808) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[23:23:27] [Server thread/INFO] [OpenEye]: openeye.logic.ThrowableLogger.processThrowable(ThrowableLogger.java:84): Limit reached for location tile_entity_write, skipping java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
[23:23:27] [Server thread/ERROR] [FML]: A TileEntity type com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
    at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
    at com.shad0wb1ade.solarexpansion.tile.BaseModTileEntity.func_145841_b(BaseModTileEntity.java:28) ~[BaseModTileEntity.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:808) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[23:23:27] [Server thread/INFO] [OpenEye]: openeye.logic.ThrowableLogger.processThrowable(ThrowableLogger.java:84): Limit reached for location tile_entity_write, skipping java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
[23:23:27] [Server thread/ERROR] [FML]: A TileEntity type com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
    at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
    at com.shad0wb1ade.solarexpansion.tile.BaseModTileEntity.func_145841_b(BaseModTileEntity.java:28) ~[BaseModTileEntity.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:808) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
java.lang.NullPointerException
    at mods.helpfulvillagers.main.CommonHooks.serverTickEventHandler(CommonHooks.java:126)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_492_CommonHooks_serverTickEventHandler_ServerTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
java.lang.NullPointerException
    at mods.helpfulvillagers.main.CommonHooks.serverTickEventHandler(CommonHooks.java:126)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_492_CommonHooks_serverTickEventHandler_ServerTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122)
    at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:536)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[23:24:12] [Server thread/INFO] [OpenEye]: openeye.logic.ThrowableLogger.processThrowable(ThrowableLogger.java:84): Limit reached for location tile_entity_write, skipping java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
[23:24:12] [Server thread/ERROR] [FML]: A TileEntity type com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
    at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
    at com.shad0wb1ade.solarexpansion.tile.BaseModTileEntity.func_145841_b(BaseModTileEntity.java:28) ~[BaseModTileEntity.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:808) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[23:24:12] [Server thread/INFO] [OpenEye]: openeye.logic.ThrowableLogger.processThrowable(ThrowableLogger.java:84): Limit reached for location tile_entity_write, skipping java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
[23:24:12] [Server thread/ERROR] [FML]: A TileEntity type com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
    at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
    at com.shad0wb1ade.solarexpansion.tile.BaseModTileEntity.func_145841_b(BaseModTileEntity.java:28) ~[BaseModTileEntity.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:808) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[23:24:12] [Server thread/INFO] [OpenEye]: openeye.logic.ThrowableLogger.processThrowable(ThrowableLogger.java:84): Limit reached for location tile_entity_write, skipping java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
[23:24:12] [Server thread/ERROR] [FML]: A TileEntity type com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
    at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
    at com.shad0wb1ade.solarexpansion.tile.BaseModTileEntity.func_145841_b(BaseModTileEntity.java:28) ~[BaseModTileEntity.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:808) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[23:24:12] [Server thread/INFO] [OpenEye]: openeye.logic.ThrowableLogger.processThrowable(ThrowableLogger.java:84): Limit reached for location tile_entity_write, skipping java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
[23:24:12] [Server thread/ERROR] [FML]: A TileEntity type com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class com.shad0wb1ade.solarexpansion.blocks.SolarPanelTileEntity is missing a mapping! This is a bug!
    at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
    at com.shad0wb1ade.solarexpansion.tile.BaseModTileEntity.func_145841_b(BaseModTileEntity.java:28) ~[BaseModTileEntity.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:808) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by trismegistis** [comment]
I get this issue too

 openeye.logic.ThrowableLogger.processThrowable(ThrowableLogger.java:84): Limit reached for location tile_entity_write, skipping java.lang.RuntimeException: class codechicken.multipart.handler.MultipartSaveLoad$TileNBTContainer is missing a mapping! This is a bug!

**Comment by trismegistis** [comment]
and it spams sometimes.. sometimes just once or twice.. sometimes spams until we crash

**Comment by Shad0wB1ade** [comment]
This issue has already been fixed. The issue you are getting has to do with codechicken stuff not mine...
So basically you have to report the issue to chickenbones. The author of that mod.

**Comment by trismegistis** [comment]
Thanks
